

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}

  
  web:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - PUID=${UID}
      - PGID=${GID}


      