# Generated by Django 5.1 on 2024-08-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_grow_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growreading',
            name='moisture_3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
