# Generated by Django 5.1 on 2024-08-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_grow_dash', '0003_rename_timestmap_growreading_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growreading',
            old_name='light',
            new_name='luminance',
        ),
        migrations.RenameField(
            model_name='growreading',
            old_name='moisture_1',
            new_name='moisture_a',
        ),
        migrations.RenameField(
            model_name='growreading',
            old_name='moisture_2',
            new_name='moisture_b',
        ),
        migrations.RenameField(
            model_name='growreading',
            old_name='moisture_3',
            new_name='moisture_c',
        ),
        migrations.RemoveField(
            model_name='growreading',
            name='voltage',
        ),
    ]
