# Generated by Django 5.1 on 2024-08-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_grow_dash', '0005_board_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='pi_grow_dash.board'),
        ),
    ]
