# Generated by Django 5.1 on 2024-08-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_grow_dash', '0006_alter_reading_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrowReading',
        ),
    ]

