# Generated by Django 5.1 on 2024-08-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_grow_dash', '0007_delete_growreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='uid',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
